package modelos;
// Generated 16/04/2015 11:54:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chofer generated by hbm2java
 */
@Entity
@Table(name="chofer"
    ,catalog="sgstt"
)
public class Chofer  implements java.io.Serializable {


     private Integer idchofer;
     private String nombre;
     private String apellido;
     private int dni;
     private Set vehiculoHasChofers = new HashSet(0);

    public Chofer() {
    }

	
    public Chofer(String nombre, String apellido, int dni) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
    }
    public Chofer(String nombre, String apellido, int dni, Set vehiculoHasChofers) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.vehiculoHasChofers = vehiculoHasChofers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idchofer", unique=true, nullable=false)
    public Integer getIdchofer() {
        return this.idchofer;
    }
    
    public void setIdchofer(Integer idchofer) {
        this.idchofer = idchofer;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="dni", nullable=false)
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chofer")
    public Set getVehiculoHasChofers() {
        return this.vehiculoHasChofers;
    }
    
    public void setVehiculoHasChofers(Set vehiculoHasChofers) {
        this.vehiculoHasChofers = vehiculoHasChofers;
    }




}


