package modelos;
// Generated 29-abr-2015 10:53:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chofer generated by hbm2java
 */
@Entity
@Table(name="chofer"
    ,catalog="sgstt"
)
public class Chofer  implements java.io.Serializable {


     private Integer idchofer;
     private String nombre;
     private String apellido;
     private String dni;
     private String categoria;
     private Set vehiculoHasChofers = new HashSet(0);
     private Set incidencias = new HashSet(0);

    public Chofer() {
    }

    public Chofer(String nombre, String apellido, String dni, String categoria, Set vehiculoHasChofers, Set incidencias) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.categoria = categoria;
       this.vehiculoHasChofers = vehiculoHasChofers;
       this.incidencias = incidencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idchofer", unique=true, nullable=false)
    public Integer getIdchofer() {
        return this.idchofer;
    }
    
    public void setIdchofer(Integer idchofer) {
        this.idchofer = idchofer;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="dni", length=45)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="categoria", length=45)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chofer")
    public Set getVehiculoHasChofers() {
        return this.vehiculoHasChofers;
    }
    
    public void setVehiculoHasChofers(Set vehiculoHasChofers) {
        this.vehiculoHasChofers = vehiculoHasChofers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chofer")
    public Set getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set incidencias) {
        this.incidencias = incidencias;
    }




}


