package modelos;
// Generated 29-abr-2015 23:38:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="sgstt"
)
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private TipoCliente tipoCliente;
     private String nombre;
     private Integer idTipoDocumento;
     private Integer numeroDocumento;
     private String direccion;
     private Integer idEstado;
     private String correo;
     private String pax;
     private String idUbigeo;
     private Set personaNaturals = new HashSet(0);
     private Set agencias = new HashSet(0);
     private Set files = new HashSet(0);
     private Set personaJuridicas = new HashSet(0);

    public Cliente() {
        idCliente = 0;
        tipoCliente = new TipoCliente();
        nombre = "";
        idTipoDocumento = 0;
        numeroDocumento = 0;
        direccion = "";
        idEstado = 0;
        correo = "";
        pax = "";
        idUbigeo = "0";
    }

	
    public Cliente(int idCliente, TipoCliente tipoCliente) {
        this.idCliente = idCliente;
        this.tipoCliente = tipoCliente;
    }
    public Cliente(int idCliente, TipoCliente tipoCliente, String nombre, Integer idTipoDocumento, Integer numeroDocumento, String direccion, Integer idEstado, String correo, String pax, String idUbigeo, Set personaNaturals, Set agencias, Set files, Set personaJuridicas) {
       this.idCliente = idCliente;
       this.tipoCliente = tipoCliente;
       this.nombre = nombre;
       this.idTipoDocumento = idTipoDocumento;
       this.numeroDocumento = numeroDocumento;
       this.direccion = direccion;
       this.idEstado = idEstado;
       this.correo = correo;
       this.pax = pax;
       this.idUbigeo = idUbigeo;
       this.personaNaturals = personaNaturals;
       this.agencias = agencias;
       this.files = files;
       this.personaJuridicas = personaJuridicas;
    }
   
     @Id 

    
    @Column(name="idCliente", unique=true, nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_TipoCliente", nullable=false)
    public TipoCliente getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(TipoCliente tipoCliente) {
        this.tipoCliente = tipoCliente;
    }

    
    @Column(name="Nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="idTipoDocumento")
    public Integer getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(Integer idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }

    
    @Column(name="NumeroDocumento")
    public Integer getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(Integer numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    
    @Column(name="Direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="idEstado")
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="Correo", length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="Pax", length=45)
    public String getPax() {
        return this.pax;
    }
    
    public void setPax(String pax) {
        this.pax = pax;
    }

    
    @Column(name="id_Ubigeo", length=45)
    public String getIdUbigeo() {
        return this.idUbigeo;
    }
    
    public void setIdUbigeo(String idUbigeo) {
        this.idUbigeo = idUbigeo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente_1")
    public Set getPersonaNaturals() {
        return this.personaNaturals;
    }
    
    public void setPersonaNaturals(Set personaNaturals) {
        this.personaNaturals = personaNaturals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getAgencias() {
        return this.agencias;
    }
    
    public void setAgencias(Set agencias) {
        this.agencias = agencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getFiles() {
        return this.files;
    }
    
    public void setFiles(Set files) {
        this.files = files;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getPersonaJuridicas() {
        return this.personaJuridicas;
    }
    
    public void setPersonaJuridicas(Set personaJuridicas) {
        this.personaJuridicas = personaJuridicas;
    }




}


