package modelos;
// Generated 29-abr-2015 10:53:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Cobro generated by hbm2java
 */
@Entity
@Table(name="cobro"
    ,catalog="sgstt"
)
public class Cobro  implements java.io.Serializable {


     private int idcobro;
     private DetalleServicio detalleServicio;
     private Byte descuento;
     private Float neto;
     private Float total;

    public Cobro() {
    }

	
    public Cobro(DetalleServicio detalleServicio) {
        this.detalleServicio = detalleServicio;
    }
    public Cobro(DetalleServicio detalleServicio, Byte descuento, Float neto, Float total) {
       this.detalleServicio = detalleServicio;
       this.descuento = descuento;
       this.neto = neto;
       this.total = total;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="detalleServicio"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idcobro", unique=true, nullable=false)
    public int getIdcobro() {
        return this.idcobro;
    }
    
    public void setIdcobro(int idcobro) {
        this.idcobro = idcobro;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public DetalleServicio getDetalleServicio() {
        return this.detalleServicio;
    }
    
    public void setDetalleServicio(DetalleServicio detalleServicio) {
        this.detalleServicio = detalleServicio;
    }

    
    @Column(name="descuento")
    public Byte getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Byte descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="neto", precision=12, scale=0)
    public Float getNeto() {
        return this.neto;
    }
    
    public void setNeto(Float neto) {
        this.neto = neto;
    }

    
    @Column(name="total", precision=12, scale=0)
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }




}


