package modelos;
// Generated 28-abr-2015 13:55:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleServicio generated by hbm2java
 */
@Entity
@Table(name="detalle_servicio"
    ,catalog="sgstt"
)
public class DetalleServicio  implements java.io.Serializable {


     private String iddetalleServicio;
     private Trasladista trasladista;
     private Vuelo vuelo;
     private Date fecha;
     private Date hora;
     private String origen;
     private String destino;
     private Set servicios = new HashSet(0);

    public DetalleServicio() {
    }

	
    public DetalleServicio(String iddetalleServicio, Trasladista trasladista, Vuelo vuelo, Date fecha, Date hora, String origen, String destino) {
        this.iddetalleServicio = iddetalleServicio;
        this.trasladista = trasladista;
        this.vuelo = vuelo;
        this.fecha = fecha;
        this.hora = hora;
        this.origen = origen;
        this.destino = destino;
    }
    public DetalleServicio(String iddetalleServicio, Trasladista trasladista, Vuelo vuelo, Date fecha, Date hora, String origen, String destino, Set servicios) {
       this.iddetalleServicio = iddetalleServicio;
       this.trasladista = trasladista;
       this.vuelo = vuelo;
       this.fecha = fecha;
       this.hora = hora;
       this.origen = origen;
       this.destino = destino;
       this.servicios = servicios;
    }
   
     @Id 

    
    @Column(name="iddetalle_servicio", unique=true, nullable=false, length=4)
    public String getIddetalleServicio() {
        return this.iddetalleServicio;
    }
    
    public void setIddetalleServicio(String iddetalleServicio) {
        this.iddetalleServicio = iddetalleServicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtrasladista", nullable=false)
    public Trasladista getTrasladista() {
        return this.trasladista;
    }
    
    public void setTrasladista(Trasladista trasladista) {
        this.trasladista = trasladista;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idvuelo", nullable=false)
    public Vuelo getVuelo() {
        return this.vuelo;
    }
    
    public void setVuelo(Vuelo vuelo) {
        this.vuelo = vuelo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hora", nullable=false, length=8)
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }

    
    @Column(name="origen", nullable=false, length=45)
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    
    @Column(name="destino", nullable=false, length=45)
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detalleServicio")
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }




}


