package modelos;
// Generated 29-abr-2015 10:53:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DetalleServicio generated by hbm2java
 */
@Entity
@Table(name="detalle_servicio"
    ,catalog="sgstt"
)
public class DetalleServicio  implements java.io.Serializable {


     private int idServicio;
     private Aerolinea aerolinea;
     private EstadoServicio estadoServicio;
     private Servicio servicio;
     private Trasladista trasladista;
     private Cobro cobro;

    public DetalleServicio() {
    }

	
    public DetalleServicio(Aerolinea aerolinea, EstadoServicio estadoServicio, Servicio servicio, Trasladista trasladista) {
        this.aerolinea = aerolinea;
        this.estadoServicio = estadoServicio;
        this.servicio = servicio;
        this.trasladista = trasladista;
    }
    public DetalleServicio(Aerolinea aerolinea, EstadoServicio estadoServicio, Servicio servicio, Trasladista trasladista, Cobro cobro) {
       this.aerolinea = aerolinea;
       this.estadoServicio = estadoServicio;
       this.servicio = servicio;
       this.trasladista = trasladista;
       this.cobro = cobro;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="servicio"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_servicio", unique=true, nullable=false)
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idaerolinea", nullable=false)
    public Aerolinea getAerolinea() {
        return this.aerolinea;
    }
    
    public void setAerolinea(Aerolinea aerolinea) {
        this.aerolinea = aerolinea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idestado_servicio", nullable=false)
    public EstadoServicio getEstadoServicio() {
        return this.estadoServicio;
    }
    
    public void setEstadoServicio(EstadoServicio estadoServicio) {
        this.estadoServicio = estadoServicio;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtrasladista", nullable=false)
    public Trasladista getTrasladista() {
        return this.trasladista;
    }
    
    public void setTrasladista(Trasladista trasladista) {
        this.trasladista = trasladista;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="detalleServicio")
    public Cobro getCobro() {
        return this.cobro;
    }
    
    public void setCobro(Cobro cobro) {
        this.cobro = cobro;
    }




}


