package modelos;
// Generated 29-abr-2015 8:17:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoIncidencia generated by hbm2java
 */
@Entity
@Table(name="estado_incidencia"
    ,catalog="sgstt"
)
public class EstadoIncidencia  implements java.io.Serializable {


     private Integer idestadoIncidencia;
     private String descripcion;
     private Set incidencias = new HashSet(0);

    public EstadoIncidencia() {
    }

    public EstadoIncidencia(String descripcion, Set incidencias) {
       this.descripcion = descripcion;
       this.incidencias = incidencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idestado_incidencia", unique=true, nullable=false)
    public Integer getIdestadoIncidencia() {
        return this.idestadoIncidencia;
    }
    
    public void setIdestadoIncidencia(Integer idestadoIncidencia) {
        this.idestadoIncidencia = idestadoIncidencia;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoIncidencia")
    public Set getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set incidencias) {
        this.incidencias = incidencias;
    }




}


