package modelos;
// Generated 29-abr-2015 10:53:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name="file"
    ,catalog="sgstt"
)
public class File  implements java.io.Serializable {


     private int idFile;
     private Cliente cliente;
     private Servicio servicio;

    public File() {
    }

    public File(int idFile, Cliente cliente, Servicio servicio) {
       this.idFile = idFile;
       this.cliente = cliente;
       this.servicio = servicio;
    }
   
     @Id 

    
    @Column(name="idFile", unique=true, nullable=false)
    public int getIdFile() {
        return this.idFile;
    }
    
    public void setIdFile(int idFile) {
        this.idFile = idFile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idservicio", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }




}


