package modelos;
// Generated 28-abr-2015 13:55:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Igv generated by hbm2java
 */
@Entity
@Table(name="igv"
    ,catalog="sgstt"
)
public class Igv  implements java.io.Serializable {


     private int idigv;
     private String monto;

    public Igv() {
    }

	
    public Igv(int idigv) {
        this.idigv = idigv;
    }
    public Igv(int idigv, String monto) {
       this.idigv = idigv;
       this.monto = monto;
    }
   
     @Id 

    
    @Column(name="idigv", unique=true, nullable=false)
    public int getIdigv() {
        return this.idigv;
    }
    
    public void setIdigv(int idigv) {
        this.idigv = idigv;
    }

    
    @Column(name="monto", length=45)
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }




}


