package modelos;
// Generated 29-abr-2015 23:38:15 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Incidencia generated by hbm2java
 */
@Entity
@Table(name="incidencia"
    ,catalog="sgstt"
)
public class Incidencia  implements java.io.Serializable {


     private int idincidencia;
     private Chofer chofer;
     private EstadoIncidencia estadoIncidencia;
     private TipoIncidencia tipoIncidencia;
     private String descripcion;

    public Incidencia() {
    }

	
    public Incidencia(int idincidencia, Chofer chofer, EstadoIncidencia estadoIncidencia, TipoIncidencia tipoIncidencia) {
        this.idincidencia = idincidencia;
        this.chofer = chofer;
        this.estadoIncidencia = estadoIncidencia;
        this.tipoIncidencia = tipoIncidencia;
    }
    public Incidencia(int idincidencia, Chofer chofer, EstadoIncidencia estadoIncidencia, TipoIncidencia tipoIncidencia, String descripcion) {
       this.idincidencia = idincidencia;
       this.chofer = chofer;
       this.estadoIncidencia = estadoIncidencia;
       this.tipoIncidencia = tipoIncidencia;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="idincidencia", unique=true, nullable=false)
    public int getIdincidencia() {
        return this.idincidencia;
    }
    
    public void setIdincidencia(int idincidencia) {
        this.idincidencia = idincidencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chofer_idchofer", nullable=false)
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado_incidencia_idestado_incidencia", nullable=false)
    public EstadoIncidencia getEstadoIncidencia() {
        return this.estadoIncidencia;
    }
    
    public void setEstadoIncidencia(EstadoIncidencia estadoIncidencia) {
        this.estadoIncidencia = estadoIncidencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_incidencia_idtipo_incidencia", nullable=false)
    public TipoIncidencia getTipoIncidencia() {
        return this.tipoIncidencia;
    }
    
    public void setTipoIncidencia(TipoIncidencia tipoIncidencia) {
        this.tipoIncidencia = tipoIncidencia;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


