package modelos;
// Generated 28-abr-2015 13:55:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pax generated by hbm2java
 */
@Entity
@Table(name="pax"
    ,catalog="sgstt"
)
public class Pax  implements java.io.Serializable {


     private int idPax;
     private String nombrePax;
     private byte cantidadPersonas;
     private Set servicios = new HashSet(0);

    public Pax() {
    }

	
    public Pax(int idPax, String nombrePax, byte cantidadPersonas) {
        this.idPax = idPax;
        this.nombrePax = nombrePax;
        this.cantidadPersonas = cantidadPersonas;
    }
    public Pax(int idPax, String nombrePax, byte cantidadPersonas, Set servicios) {
       this.idPax = idPax;
       this.nombrePax = nombrePax;
       this.cantidadPersonas = cantidadPersonas;
       this.servicios = servicios;
    }
   
     @Id 

    
    @Column(name="idPAX", unique=true, nullable=false)
    public int getIdPax() {
        return this.idPax;
    }
    
    public void setIdPax(int idPax) {
        this.idPax = idPax;
    }

    
    @Column(name="nombre_PAX", nullable=false, length=30)
    public String getNombrePax() {
        return this.nombrePax;
    }
    
    public void setNombrePax(String nombrePax) {
        this.nombrePax = nombrePax;
    }

    
    @Column(name="cantidad_personas", nullable=false)
    public byte getCantidadPersonas() {
        return this.cantidadPersonas;
    }
    
    public void setCantidadPersonas(byte cantidadPersonas) {
        this.cantidadPersonas = cantidadPersonas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pax")
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }




}


