package modelos;
// Generated 29-abr-2015 8:17:58 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonaNatural generated by hbm2java
 */
@Entity
@Table(name="persona_natural"
    ,catalog="sgstt"
)
public class PersonaNatural  implements java.io.Serializable {


     private String cliente;
     private Cliente cliente_1;
     private int apellidos;

    public PersonaNatural() {
    }

    public PersonaNatural(String cliente, Cliente cliente_1, int apellidos) {
       this.cliente = cliente;
       this.cliente_1 = cliente_1;
       this.apellidos = apellidos;
    }
   
     @Id 

    
    @Column(name="Cliente", unique=true, nullable=false, length=45)
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_idCliente", nullable=false)
    public Cliente getCliente_1() {
        return this.cliente_1;
    }
    
    public void setCliente_1(Cliente cliente_1) {
        this.cliente_1 = cliente_1;
    }

    
    @Column(name="Apellidos", nullable=false)
    public int getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(int apellidos) {
        this.apellidos = apellidos;
    }




}


