package modelos;
// Generated 29-abr-2015 23:38:15 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonaJuridica generated by hbm2java
 */
@Entity
@Table(name="persona juridica"
    ,catalog="sgstt"
)
public class PersonaJuridica  implements java.io.Serializable {


     private Integer idcliente;
     private Cliente cliente;

    public PersonaJuridica() {
        idcliente = 0;
        cliente = new Cliente();
    }

    public PersonaJuridica(Cliente cliente) {
       this.cliente = cliente;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcliente", unique=true, nullable=false)
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }




}


