package modelos;
// Generated 29-abr-2015 8:17:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name="servicio"
    ,catalog="sgstt"
)
public class Servicio  implements java.io.Serializable {


     private Integer idservicio;
     private Tarifa tarifa;
     private TipoServicio tipoServicio;
     private String descripcion;
     private Integer numeroPersonas;
     private Set vehiculoHasServicios = new HashSet(0);
     private Set files = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(Tarifa tarifa, TipoServicio tipoServicio) {
        this.tarifa = tarifa;
        this.tipoServicio = tipoServicio;
    }
    public Servicio(Tarifa tarifa, TipoServicio tipoServicio, String descripcion, Integer numeroPersonas, Set vehiculoHasServicios, Set files) {
       this.tarifa = tarifa;
       this.tipoServicio = tipoServicio;
       this.descripcion = descripcion;
       this.numeroPersonas = numeroPersonas;
       this.vehiculoHasServicios = vehiculoHasServicios;
       this.files = files;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idservicio", unique=true, nullable=false)
    public Integer getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(Integer idservicio) {
        this.idservicio = idservicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTarifa", nullable=false)
    public Tarifa getTarifa() {
        return this.tarifa;
    }
    
    public void setTarifa(Tarifa tarifa) {
        this.tarifa = tarifa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtipo_servicio", nullable=false)
    public TipoServicio getTipoServicio() {
        return this.tipoServicio;
    }
    
    public void setTipoServicio(TipoServicio tipoServicio) {
        this.tipoServicio = tipoServicio;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="numeroPersonas")
    public Integer getNumeroPersonas() {
        return this.numeroPersonas;
    }
    
    public void setNumeroPersonas(Integer numeroPersonas) {
        this.numeroPersonas = numeroPersonas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set getVehiculoHasServicios() {
        return this.vehiculoHasServicios;
    }
    
    public void setVehiculoHasServicios(Set vehiculoHasServicios) {
        this.vehiculoHasServicios = vehiculoHasServicios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set getFiles() {
        return this.files;
    }
    
    public void setFiles(Set files) {
        this.files = files;
    }




}


