package modelos;
// Generated 29-abr-2015 10:53:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name="servicio"
    ,catalog="sgstt"
)
public class Servicio  implements java.io.Serializable {


     private Integer idservicio;
     private Tarifa tarifa;
     private TipoServicio tipoServicio;
     private Integer numeroPersonas;
     private String hora;
     private String fecha;
     private Set vehiculoHasServicios = new HashSet(0);
     private DetalleServicio detalleServicio;
     private Set files = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(Tarifa tarifa, TipoServicio tipoServicio, String hora, String fecha) {
        this.tarifa = tarifa;
        this.tipoServicio = tipoServicio;
        this.hora = hora;
        this.fecha = fecha;
    }
    public Servicio(Tarifa tarifa, TipoServicio tipoServicio, Integer numeroPersonas, String hora, String fecha, Set vehiculoHasServicios, DetalleServicio detalleServicio, Set files) {
       this.tarifa = tarifa;
       this.tipoServicio = tipoServicio;
       this.numeroPersonas = numeroPersonas;
       this.hora = hora;
       this.fecha = fecha;
       this.vehiculoHasServicios = vehiculoHasServicios;
       this.detalleServicio = detalleServicio;
       this.files = files;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idservicio", unique=true, nullable=false)
    public Integer getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(Integer idservicio) {
        this.idservicio = idservicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTarifa", nullable=false)
    public Tarifa getTarifa() {
        return this.tarifa;
    }
    
    public void setTarifa(Tarifa tarifa) {
        this.tarifa = tarifa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtipo_servicio", nullable=false)
    public TipoServicio getTipoServicio() {
        return this.tipoServicio;
    }
    
    public void setTipoServicio(TipoServicio tipoServicio) {
        this.tipoServicio = tipoServicio;
    }

    
    @Column(name="numeroPersonas")
    public Integer getNumeroPersonas() {
        return this.numeroPersonas;
    }
    
    public void setNumeroPersonas(Integer numeroPersonas) {
        this.numeroPersonas = numeroPersonas;
    }

    
    @Column(name="hora", nullable=false, length=45)
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

    
    @Column(name="fecha", nullable=false, length=45)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set getVehiculoHasServicios() {
        return this.vehiculoHasServicios;
    }
    
    public void setVehiculoHasServicios(Set vehiculoHasServicios) {
        this.vehiculoHasServicios = vehiculoHasServicios;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="servicio")
    public DetalleServicio getDetalleServicio() {
        return this.detalleServicio;
    }
    
    public void setDetalleServicio(DetalleServicio detalleServicio) {
        this.detalleServicio = detalleServicio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set getFiles() {
        return this.files;
    }
    
    public void setFiles(Set files) {
        this.files = files;
    }




}


