package modelos;
// Generated 29-abr-2015 23:38:15 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServicioDetalle generated by hbm2java
 */
@Entity
@Table(name="servicio_detalle"
    ,catalog="sgstt"
)
public class ServicioDetalle  implements java.io.Serializable {


     private Integer idservicioDetalle;
     private Aerolinea aerolinea;
     private Cobro cobro;
     private EstadoServicio estadoServicio;
     private Servicio servicio;
     private Trasladista trasladista;
     private int numPersonas;

    public ServicioDetalle() {
    }

    public ServicioDetalle(Aerolinea aerolinea, Cobro cobro, EstadoServicio estadoServicio, Servicio servicio, Trasladista trasladista, int numPersonas) {
       this.aerolinea = aerolinea;
       this.cobro = cobro;
       this.estadoServicio = estadoServicio;
       this.servicio = servicio;
       this.trasladista = trasladista;
       this.numPersonas = numPersonas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idservicio_detalle", unique=true, nullable=false)
    public Integer getIdservicioDetalle() {
        return this.idservicioDetalle;
    }
    
    public void setIdservicioDetalle(Integer idservicioDetalle) {
        this.idservicioDetalle = idservicioDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idaerolinea", nullable=false)
    public Aerolinea getAerolinea() {
        return this.aerolinea;
    }
    
    public void setAerolinea(Aerolinea aerolinea) {
        this.aerolinea = aerolinea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcobro", nullable=false)
    public Cobro getCobro() {
        return this.cobro;
    }
    
    public void setCobro(Cobro cobro) {
        this.cobro = cobro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idestado_servicio", nullable=false)
    public EstadoServicio getEstadoServicio() {
        return this.estadoServicio;
    }
    
    public void setEstadoServicio(EstadoServicio estadoServicio) {
        this.estadoServicio = estadoServicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idservicio", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtrasladista", nullable=false)
    public Trasladista getTrasladista() {
        return this.trasladista;
    }
    
    public void setTrasladista(Trasladista trasladista) {
        this.trasladista = trasladista;
    }

    
    @Column(name="num_personas", nullable=false)
    public int getNumPersonas() {
        return this.numPersonas;
    }
    
    public void setNumPersonas(int numPersonas) {
        this.numPersonas = numPersonas;
    }




}


