package modelos;
// Generated 29-abr-2015 23:38:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name="servicio"
    ,catalog="sgstt"
)
public class Servicio  implements java.io.Serializable {


     private Integer idservicio;
     private TipoServicio tipoServicio;
     private String origen;
     private String destino;
     private String fecha;
     private String hora;
     private String direccion;
     private String descripcion;
     private Set vehiculoHasChoferHasServicios = new HashSet(0);
     private Set servicioDetalles = new HashSet(0);
     private Set files = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(TipoServicio tipoServicio) {
        this.tipoServicio = tipoServicio;
    }
    public Servicio(TipoServicio tipoServicio, String origen, String destino, String fecha, String hora, String direccion, String descripcion, Set vehiculoHasChoferHasServicios, Set servicioDetalles, Set files) {
       this.tipoServicio = tipoServicio;
       this.origen = origen;
       this.destino = destino;
       this.fecha = fecha;
       this.hora = hora;
       this.direccion = direccion;
       this.descripcion = descripcion;
       this.vehiculoHasChoferHasServicios = vehiculoHasChoferHasServicios;
       this.servicioDetalles = servicioDetalles;
       this.files = files;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idservicio", unique=true, nullable=false)
    public Integer getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(Integer idservicio) {
        this.idservicio = idservicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtipo_servicio", nullable=false)
    public TipoServicio getTipoServicio() {
        return this.tipoServicio;
    }
    
    public void setTipoServicio(TipoServicio tipoServicio) {
        this.tipoServicio = tipoServicio;
    }

    
    @Column(name="origen", length=45)
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    
    @Column(name="destino", length=45)
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }

    
    @Column(name="fecha", length=45)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="hora", length=45)
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set getVehiculoHasChoferHasServicios() {
        return this.vehiculoHasChoferHasServicios;
    }
    
    public void setVehiculoHasChoferHasServicios(Set vehiculoHasChoferHasServicios) {
        this.vehiculoHasChoferHasServicios = vehiculoHasChoferHasServicios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set getServicioDetalles() {
        return this.servicioDetalles;
    }
    
    public void setServicioDetalles(Set servicioDetalles) {
        this.servicioDetalles = servicioDetalles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set getFiles() {
        return this.files;
    }
    
    public void setFiles(Set files) {
        this.files = files;
    }




}


