package modelos;
// Generated 29-abr-2015 8:17:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tarifa generated by hbm2java
 */
@Entity
@Table(name="tarifa"
    ,catalog="sgstt"
)
public class Tarifa  implements java.io.Serializable {


     private int idTarifa;
     private String precio;
     private String tipoMoneda;
     private Set servicios = new HashSet(0);

    public Tarifa() {
    }

	
    public Tarifa(int idTarifa) {
        this.idTarifa = idTarifa;
    }
    public Tarifa(int idTarifa, String precio, String tipoMoneda, Set servicios) {
       this.idTarifa = idTarifa;
       this.precio = precio;
       this.tipoMoneda = tipoMoneda;
       this.servicios = servicios;
    }
   
     @Id 

    
    @Column(name="idTarifa", unique=true, nullable=false)
    public int getIdTarifa() {
        return this.idTarifa;
    }
    
    public void setIdTarifa(int idTarifa) {
        this.idTarifa = idTarifa;
    }

    
    @Column(name="Precio", length=45)
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }

    
    @Column(name="tipoMoneda", length=45)
    public String getTipoMoneda() {
        return this.tipoMoneda;
    }
    
    public void setTipoMoneda(String tipoMoneda) {
        this.tipoMoneda = tipoMoneda;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tarifa")
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }




}


