package modelos;
// Generated 29-abr-2015 23:38:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCliente generated by hbm2java
 */
@Entity
@Table(name="tipo_cliente"
    ,catalog="sgstt"
)
public class TipoCliente  implements java.io.Serializable {


     private int idTipoCliente;
     private String tipoCliente;
     private Set clientes = new HashSet(0);

    public TipoCliente() {
        idTipoCliente = 0;
        tipoCliente = "";
    }

	
    public TipoCliente(int idTipoCliente) {
        this.idTipoCliente = idTipoCliente;
    }
    public TipoCliente(int idTipoCliente, String tipoCliente, Set clientes) {
       this.idTipoCliente = idTipoCliente;
       this.tipoCliente = tipoCliente;
       this.clientes = clientes;
    }
   
     @Id 

    
    @Column(name="id_TipoCliente", unique=true, nullable=false)
    public int getIdTipoCliente() {
        return this.idTipoCliente;
    }
    
    public void setIdTipoCliente(int idTipoCliente) {
        this.idTipoCliente = idTipoCliente;
    }

    
    @Column(name="Tipo_Cliente", length=45)
    public String getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(String tipoCliente) {
        this.tipoCliente = tipoCliente;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCliente")
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


