package modelos;
// Generated 16/04/2015 11:54:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCliente generated by hbm2java
 */
@Entity
@Table(name="tipo_cliente"
    ,catalog="sgstt"
)
public class TipoCliente  implements java.io.Serializable {


     private Integer idtipoCliente;
     private String descripcion;
     private Set clientes = new HashSet(0);

    public TipoCliente() {
    }

    public TipoCliente(String descripcion, Set clientes) {
       this.descripcion = descripcion;
       this.clientes = clientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtipo_cliente", unique=true, nullable=false)
    public Integer getIdtipoCliente() {
        return this.idtipoCliente;
    }
    
    public void setIdtipoCliente(Integer idtipoCliente) {
        this.idtipoCliente = idtipoCliente;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCliente")
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


