package modelos;
// Generated 16/04/2015 11:54:20 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ubigeo generated by hbm2java
 */
@Entity
@Table(name="ubigeo"
    ,catalog="sgstt"
)
public class Ubigeo  implements java.io.Serializable {


     private Integer cdUbigeo;
     private String codDep;
     private String codProv;
     private String codDst;
     private String region;
     private String prov;
     private String dst;

    public Ubigeo() {
    }

    public Ubigeo(String codDep, String codProv, String codDst, String region, String prov, String dst) {
       this.codDep = codDep;
       this.codProv = codProv;
       this.codDst = codDst;
       this.region = region;
       this.prov = prov;
       this.dst = dst;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Cd_Ubigeo", unique=true, nullable=false)
    public Integer getCdUbigeo() {
        return this.cdUbigeo;
    }
    
    public void setCdUbigeo(Integer cdUbigeo) {
        this.cdUbigeo = cdUbigeo;
    }

    
    @Column(name="CodDep", length=2)
    public String getCodDep() {
        return this.codDep;
    }
    
    public void setCodDep(String codDep) {
        this.codDep = codDep;
    }

    
    @Column(name="CodProv", length=2)
    public String getCodProv() {
        return this.codProv;
    }
    
    public void setCodProv(String codProv) {
        this.codProv = codProv;
    }

    
    @Column(name="CodDst", length=2)
    public String getCodDst() {
        return this.codDst;
    }
    
    public void setCodDst(String codDst) {
        this.codDst = codDst;
    }

    
    @Column(name="Region", length=100)
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }

    
    @Column(name="Prov", length=100)
    public String getProv() {
        return this.prov;
    }
    
    public void setProv(String prov) {
        this.prov = prov;
    }

    
    @Column(name="Dst", length=100)
    public String getDst() {
        return this.dst;
    }
    
    public void setDst(String dst) {
        this.dst = dst;
    }




}


