package modelos;
// Generated 29-abr-2015 10:53:26 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="sgstt"
)
public class Usuario  implements java.io.Serializable {


     private UsuarioId id;
     private Perfil perfil;
     private String nick;
     private String clave;
     private String nombre;
     private String apellido;
     private byte estado;

    public Usuario() {
    }

	
    public Usuario(UsuarioId id, Perfil perfil, String nick, String nombre, String apellido, byte estado) {
        this.id = id;
        this.perfil = perfil;
        this.nick = nick;
        this.nombre = nombre;
        this.apellido = apellido;
        this.estado = estado;
    }
    public Usuario(UsuarioId id, Perfil perfil, String nick, String clave, String nombre, String apellido, byte estado) {
       this.id = id;
       this.perfil = perfil;
       this.nick = nick;
       this.clave = clave;
       this.nombre = nombre;
       this.apellido = apellido;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idusuario", column=@Column(name="idusuario", nullable=false) ), 
        @AttributeOverride(name="idRol", column=@Column(name="idRol", nullable=false) ) } )
    public UsuarioId getId() {
        return this.id;
    }
    
    public void setId(UsuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idRol", nullable=false, insertable=false, updatable=false)
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="nick", nullable=false, length=20)
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }

    
    @Column(name="clave", length=16)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="nombre", nullable=false, length=60)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=80)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="estado", nullable=false)
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }




}


