package modelos;
// Generated 16/04/2015 11:54:20 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VehiculoHasChofer generated by hbm2java
 */
@Entity
@Table(name="vehiculo_has_chofer"
    ,catalog="sgstt"
)
public class VehiculoHasChofer  implements java.io.Serializable {


     private VehiculoHasChoferId id;
     private Chofer chofer;
     private Vehiculo vehiculo;
     private int idServicio;

    public VehiculoHasChofer() {
    }

    public VehiculoHasChofer(VehiculoHasChoferId id, Chofer chofer, Vehiculo vehiculo, int idServicio) {
       this.id = id;
       this.chofer = chofer;
       this.vehiculo = vehiculo;
       this.idServicio = idServicio;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="dvehiculo", column=@Column(name="dvehiculo", nullable=false) ), 
        @AttributeOverride(name="idchofer", column=@Column(name="idchofer", nullable=false) ) } )
    public VehiculoHasChoferId getId() {
        return this.id;
    }
    
    public void setId(VehiculoHasChoferId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idchofer", nullable=false, insertable=false, updatable=false)
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dvehiculo", nullable=false, insertable=false, updatable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="id_servicio", nullable=false)
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }




}


