package modelos;
// Generated 28-abr-2015 13:55:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VehiculoHasServicioId generated by hbm2java
 */
@Embeddable
public class VehiculoHasServicioId  implements java.io.Serializable {


     private int vehiculoIdvehiculo;
     private int servicioIdservicio;

    public VehiculoHasServicioId() {
    }

    public VehiculoHasServicioId(int vehiculoIdvehiculo, int servicioIdservicio) {
       this.vehiculoIdvehiculo = vehiculoIdvehiculo;
       this.servicioIdservicio = servicioIdservicio;
    }
   


    @Column(name="vehiculo_idvehiculo", nullable=false)
    public int getVehiculoIdvehiculo() {
        return this.vehiculoIdvehiculo;
    }
    
    public void setVehiculoIdvehiculo(int vehiculoIdvehiculo) {
        this.vehiculoIdvehiculo = vehiculoIdvehiculo;
    }


    @Column(name="servicio_idservicio", nullable=false)
    public int getServicioIdservicio() {
        return this.servicioIdservicio;
    }
    
    public void setServicioIdservicio(int servicioIdservicio) {
        this.servicioIdservicio = servicioIdservicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VehiculoHasServicioId) ) return false;
		 VehiculoHasServicioId castOther = ( VehiculoHasServicioId ) other; 
         
		 return (this.getVehiculoIdvehiculo()==castOther.getVehiculoIdvehiculo())
 && (this.getServicioIdservicio()==castOther.getServicioIdservicio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVehiculoIdvehiculo();
         result = 37 * result + this.getServicioIdservicio();
         return result;
   }   


}


