package modelos;
// Generated 29-abr-2015 10:53:26 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VehiculoHasChofer generated by hbm2java
 */
@Entity
@Table(name="vehiculo_has_chofer"
    ,catalog="sgstt"
)
public class VehiculoHasChofer  implements java.io.Serializable {


     private VehiculoHasChoferId id;
     private Chofer chofer;
     private Vehiculo vehiculo;
     private String observaciones;

    public VehiculoHasChofer() {
    }

	
    public VehiculoHasChofer(VehiculoHasChoferId id, Chofer chofer, Vehiculo vehiculo) {
        this.id = id;
        this.chofer = chofer;
        this.vehiculo = vehiculo;
    }
    public VehiculoHasChofer(VehiculoHasChoferId id, Chofer chofer, Vehiculo vehiculo, String observaciones) {
       this.id = id;
       this.chofer = chofer;
       this.vehiculo = vehiculo;
       this.observaciones = observaciones;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idvehiculo", column=@Column(name="idvehiculo", nullable=false) ), 
        @AttributeOverride(name="idchofer", column=@Column(name="idchofer", nullable=false) ) } )
    public VehiculoHasChoferId getId() {
        return this.id;
    }
    
    public void setId(VehiculoHasChoferId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idchofer", nullable=false, insertable=false, updatable=false)
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idvehiculo", nullable=false, insertable=false, updatable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="observaciones", length=65535)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


