package modelos;
// Generated 29-abr-2015 23:38:15 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VehiculoHasChoferHasServicio generated by hbm2java
 */
@Entity
@Table(name="vehiculo_has_chofer_has_servicio"
    ,catalog="sgstt"
)
public class VehiculoHasChoferHasServicio  implements java.io.Serializable {


     private VehiculoHasChoferHasServicioId id;
     private Servicio servicio;
     private VehiculoHasChofer vehiculoHasChofer;
     private String observaciones;

    public VehiculoHasChoferHasServicio() {
    }

	
    public VehiculoHasChoferHasServicio(VehiculoHasChoferHasServicioId id, Servicio servicio, VehiculoHasChofer vehiculoHasChofer) {
        this.id = id;
        this.servicio = servicio;
        this.vehiculoHasChofer = vehiculoHasChofer;
    }
    public VehiculoHasChoferHasServicio(VehiculoHasChoferHasServicioId id, Servicio servicio, VehiculoHasChofer vehiculoHasChofer, String observaciones) {
       this.id = id;
       this.servicio = servicio;
       this.vehiculoHasChofer = vehiculoHasChofer;
       this.observaciones = observaciones;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idVehiculoHasChofer", column=@Column(name="id_vehiculo_has_chofer", nullable=false) ), 
        @AttributeOverride(name="idservicio", column=@Column(name="idservicio", nullable=false) ) } )
    public VehiculoHasChoferHasServicioId getId() {
        return this.id;
    }
    
    public void setId(VehiculoHasChoferHasServicioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idservicio", nullable=false, insertable=false, updatable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vehiculo_has_chofer", nullable=false, insertable=false, updatable=false)
    public VehiculoHasChofer getVehiculoHasChofer() {
        return this.vehiculoHasChofer;
    }
    
    public void setVehiculoHasChofer(VehiculoHasChofer vehiculoHasChofer) {
        this.vehiculoHasChofer = vehiculoHasChofer;
    }

    
    @Column(name="observaciones", length=65535)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


