package modelos;
// Generated 29-abr-2015 8:17:58 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VehiculoHasServicioId generated by hbm2java
 */
@Embeddable
public class VehiculoHasServicioId  implements java.io.Serializable {


     private int idvehiculo;
     private int idservicio;

    public VehiculoHasServicioId() {
    }

    public VehiculoHasServicioId(int idvehiculo, int idservicio) {
       this.idvehiculo = idvehiculo;
       this.idservicio = idservicio;
    }
   


    @Column(name="idvehiculo", nullable=false)
    public int getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(int idvehiculo) {
        this.idvehiculo = idvehiculo;
    }


    @Column(name="idservicio", nullable=false)
    public int getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(int idservicio) {
        this.idservicio = idservicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VehiculoHasServicioId) ) return false;
		 VehiculoHasServicioId castOther = ( VehiculoHasServicioId ) other; 
         
		 return (this.getIdvehiculo()==castOther.getIdvehiculo())
 && (this.getIdservicio()==castOther.getIdservicio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdvehiculo();
         result = 37 * result + this.getIdservicio();
         return result;
   }   


}


