package modelos;
// Generated 16/04/2015 11:54:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="vehiculo"
    ,catalog="sgstt"
)
public class Vehiculo  implements java.io.Serializable {


     private Integer idvehiculo;
     private String descripcion;
     private String placa;
     private String estado;
     private Set vehiculoHasServicios = new HashSet(0);
     private Set vehiculoHasChofers = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String descripcion, String placa, String estado) {
        this.descripcion = descripcion;
        this.placa = placa;
        this.estado = estado;
    }
    public Vehiculo(String descripcion, String placa, String estado, Set vehiculoHasServicios, Set vehiculoHasChofers) {
       this.descripcion = descripcion;
       this.placa = placa;
       this.estado = estado;
       this.vehiculoHasServicios = vehiculoHasServicios;
       this.vehiculoHasChofers = vehiculoHasChofers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idvehiculo", unique=true, nullable=false)
    public Integer getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(Integer idvehiculo) {
        this.idvehiculo = idvehiculo;
    }

    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="placa", nullable=false, length=45)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

    
    @Column(name="estado", nullable=false, length=13)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set getVehiculoHasServicios() {
        return this.vehiculoHasServicios;
    }
    
    public void setVehiculoHasServicios(Set vehiculoHasServicios) {
        this.vehiculoHasServicios = vehiculoHasServicios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set getVehiculoHasChofers() {
        return this.vehiculoHasChofers;
    }
    
    public void setVehiculoHasChofers(Set vehiculoHasChofers) {
        this.vehiculoHasChofers = vehiculoHasChofers;
    }




}


