package modelos;
// Generated 29-abr-2015 10:53:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VehiculoHasChoferId generated by hbm2java
 */
@Embeddable
public class VehiculoHasChoferId  implements java.io.Serializable {


     private int idvehiculo;
     private int idchofer;

    public VehiculoHasChoferId() {
    }

    public VehiculoHasChoferId(int idvehiculo, int idchofer) {
       this.idvehiculo = idvehiculo;
       this.idchofer = idchofer;
    }
   


    @Column(name="idvehiculo", nullable=false)
    public int getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(int idvehiculo) {
        this.idvehiculo = idvehiculo;
    }


    @Column(name="idchofer", nullable=false)
    public int getIdchofer() {
        return this.idchofer;
    }
    
    public void setIdchofer(int idchofer) {
        this.idchofer = idchofer;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VehiculoHasChoferId) ) return false;
		 VehiculoHasChoferId castOther = ( VehiculoHasChoferId ) other; 
         
		 return (this.getIdvehiculo()==castOther.getIdvehiculo())
 && (this.getIdchofer()==castOther.getIdchofer());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdvehiculo();
         result = 37 * result + this.getIdchofer();
         return result;
   }   


}


