package modelos;
// Generated 29-abr-2015 8:17:58 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VueloId generated by hbm2java
 */
@Embeddable
public class VueloId  implements java.io.Serializable {


     private int idvuelo;
     private int aerolineaIdaerolinea;

    public VueloId() {
    }

    public VueloId(int idvuelo, int aerolineaIdaerolinea) {
       this.idvuelo = idvuelo;
       this.aerolineaIdaerolinea = aerolineaIdaerolinea;
    }
   


    @Column(name="idvuelo", nullable=false)
    public int getIdvuelo() {
        return this.idvuelo;
    }
    
    public void setIdvuelo(int idvuelo) {
        this.idvuelo = idvuelo;
    }


    @Column(name="aerolinea_idaerolinea", nullable=false)
    public int getAerolineaIdaerolinea() {
        return this.aerolineaIdaerolinea;
    }
    
    public void setAerolineaIdaerolinea(int aerolineaIdaerolinea) {
        this.aerolineaIdaerolinea = aerolineaIdaerolinea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VueloId) ) return false;
		 VueloId castOther = ( VueloId ) other; 
         
		 return (this.getIdvuelo()==castOther.getIdvuelo())
 && (this.getAerolineaIdaerolinea()==castOther.getAerolineaIdaerolinea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdvuelo();
         result = 37 * result + this.getAerolineaIdaerolinea();
         return result;
   }   


}


