package modelos;
// Generated 29-abr-2015 8:17:58 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vuelo generated by hbm2java
 */
@Entity
@Table(name="vuelo"
    ,catalog="sgstt"
)
public class Vuelo  implements java.io.Serializable {


     private VueloId id;
     private Aerolinea aerolinea;
     private String origen;
     private String destino;
     private String horario;

    public Vuelo() {
    }

	
    public Vuelo(VueloId id, Aerolinea aerolinea) {
        this.id = id;
        this.aerolinea = aerolinea;
    }
    public Vuelo(VueloId id, Aerolinea aerolinea, String origen, String destino, String horario) {
       this.id = id;
       this.aerolinea = aerolinea;
       this.origen = origen;
       this.destino = destino;
       this.horario = horario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idvuelo", column=@Column(name="idvuelo", nullable=false) ), 
        @AttributeOverride(name="aerolineaIdaerolinea", column=@Column(name="aerolinea_idaerolinea", nullable=false) ) } )
    public VueloId getId() {
        return this.id;
    }
    
    public void setId(VueloId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aerolinea_idaerolinea", nullable=false, insertable=false, updatable=false)
    public Aerolinea getAerolinea() {
        return this.aerolinea;
    }
    
    public void setAerolinea(Aerolinea aerolinea) {
        this.aerolinea = aerolinea;
    }

    
    @Column(name="origen", length=45)
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    
    @Column(name="destino", length=45)
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }

    
    @Column(name="horario", length=45)
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }




}


