package modelos;
// Generated 16/04/2015 11:54:20 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vuelo generated by hbm2java
 */
@Entity
@Table(name="vuelo"
    ,catalog="sgstt"
)
public class Vuelo  implements java.io.Serializable {


     private Integer idvuelo;
     private Aerolinea aerolinea;
     private String origen;
     private String destino;
     private Date fecha;
     private Date hora;
     private Set detalleServicios = new HashSet(0);

    public Vuelo() {
    }

	
    public Vuelo(Aerolinea aerolinea, String origen, String destino, Date fecha, Date hora) {
        this.aerolinea = aerolinea;
        this.origen = origen;
        this.destino = destino;
        this.fecha = fecha;
        this.hora = hora;
    }
    public Vuelo(Aerolinea aerolinea, String origen, String destino, Date fecha, Date hora, Set detalleServicios) {
       this.aerolinea = aerolinea;
       this.origen = origen;
       this.destino = destino;
       this.fecha = fecha;
       this.hora = hora;
       this.detalleServicios = detalleServicios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idvuelo", unique=true, nullable=false)
    public Integer getIdvuelo() {
        return this.idvuelo;
    }
    
    public void setIdvuelo(Integer idvuelo) {
        this.idvuelo = idvuelo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idaerolinea", nullable=false)
    public Aerolinea getAerolinea() {
        return this.aerolinea;
    }
    
    public void setAerolinea(Aerolinea aerolinea) {
        this.aerolinea = aerolinea;
    }

    
    @Column(name="origen", nullable=false, length=45)
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    
    @Column(name="destino", nullable=false, length=45)
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hora", nullable=false, length=8)
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vuelo")
    public Set getDetalleServicios() {
        return this.detalleServicios;
    }
    
    public void setDetalleServicios(Set detalleServicios) {
        this.detalleServicios = detalleServicios;
    }




}


