package modelos;
// Generated 29-abr-2015 23:38:15 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vuelo generated by hbm2java
 */
@Entity
@Table(name="vuelo"
    ,catalog="sgstt"
)
public class Vuelo  implements java.io.Serializable {


     private Integer idvuelo;
     private Aerolinea aerolinea;
     private String origen;
     private String destino;
     private String horario;

    public Vuelo() {
        idvuelo = 0;
        aerolinea = new Aerolinea();
        origen = "";
        destino = "";
        horario = "";
    }

	
    public Vuelo(Aerolinea aerolinea) {
        this.aerolinea = aerolinea;
    }
    public Vuelo(Aerolinea aerolinea, String origen, String destino, String horario) {
       this.aerolinea = aerolinea;
       this.origen = origen;
       this.destino = destino;
       this.horario = horario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idvuelo", unique=true, nullable=false)
    public Integer getIdvuelo() {
        return this.idvuelo;
    }
    
    public void setIdvuelo(Integer idvuelo) {
        this.idvuelo = idvuelo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idaerolinea", nullable=false)
    public Aerolinea getAerolinea() {
        return this.aerolinea;
    }
    
    public void setAerolinea(Aerolinea aerolinea) {
        this.aerolinea = aerolinea;
    }

    
    @Column(name="origen", length=45)
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    
    @Column(name="destino", length=45)
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }

    
    @Column(name="horario", length=45)
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }




}


